-
    id: 1
    product_type:
        id: 4
    product_category:
        id: 1
    code: h08841993
    ticketingRight:
        -
            id: 5
-
    id: 2
    product_type:
        id: 4
    product_category:
        id: 1
    code: h08684929
-
    id: 3
    product_type:
        id: 4
    product_category:
        id: 1
    code: h08343931
-
    id: 4
    product_type:
        id: 4
    product_category:
        id: 2
    code: h16544667
-
    id: 5
    product_type:
        id: 4
    product_category:
        id: 2
    code: h16187120
-
    id: 6
    product_type:
        id: 4
    product_category:
        id: 2
    code: h16620337
-
    id: 7
    product_type:
        id: 4
    product_category:
        id: 3
    code: h36924633
-
    id: 8
    product_type:
        id: 4
    product_category:
        id: 3
    code: h36355718
-
    id: 9
    product_type:
        id: 4
    product_category:
        id: 3
    code: h36217165
-
    id: 10
    product_type:
        id: 4
    product_category:
        id: 4
    code: h00606949
-
    id: 11
    product_type:
        id: 4
    product_category:
        id: 4
    code: h00996270
-
    id: 12
    product_type:
        id: 4
    product_category:
        id: 4
    code: h00651345
-
    id: 13
    product_type:
        id: 4
    product_category:
        id: 5
    code: jp1925110
-
    id: 14
    product_type:
        id: 4
    product_category:
        id: 5
    code: jp1210302
-
    id: 15
    product_type:
        id: 4
    product_category:
        id: 5
    code: jp1708101
