### user profile endpoint
GET {{hunt_url}}/api/profile 
Authorization: Bearer {{nonProdToken}}

### all user-related data
GET {{hunt_url}}/api/me 
Authorization: Bearer {{nonProdToken}}

### Update user profile
put {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{nonProdToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="60x60bb.jpg"
Content-Type: image/jpg

< ./JonDoe.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

Mihkel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Putrinš
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### forecast by city
GET https://api.openweathermap.org/data/2.5/forecast?q=TALLINN&appid=5927bae3714473ae1f6d7541cf67a948&units=metric

### weather by lat lon
GET https://api.openweathermap.org/data/2.5/weather?lat=59.437&lon=24.7535&appid=5927bae3714473ae1f6d7541cf67a948


###
POST https://admin.poff.ee/auth/local HTTP/1.1
content-type: application/json

{
    "identifier": "mmmm@gmail.com", 
    "password": "mmmm"
}

###

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQ3ODMsImlhdCI6MTY5ODI0Nzk5NiwiZXhwIjoxNjk4MzM0Mzk2fQ.m3w1o0o--5lesULFp6tVGpdouXESrSZxMEot73EfCjw

###
POST https://admin.poff.ee/users/me/10538 HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

###

GET https://admin.poff.ee/user-profiles HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

###

GET https://admin.poff.ee/users/14813 HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

###

POST https://admin.poff.ee/auth/oauth/register HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

{
    "username": "test123",
    "email": "user@strapi.io",
    "password": "xxxxxxxxxxxx"
}

### 1 of films
GET https://admin.poff.ee/films/3212 HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

### 1 of festival-editions
GET https://admin.poff.ee/festival-editions/66 HTTP/1.1
content-type: application/json
Authorization: Bearer {{adminToken}}

