
POST https://admin.poff.ee/auth/local HTTP/1.1
content-type: application/json

{
    "identifier": "{{user}}", 
    "password": "{{secretKey}}"
}

###

GET https://admin.poff.ee/user-profiles HTTP/1.1
content-type: application/json
Authorization: Bearer {{nonProdToken}}

###

GET https://admin.poff.ee/users/16998 HTTP/1.1
content-type: application/json
Authorization: Bearer {{nonProdToken}}

###

POST https://admin.poff.ee/auth/oauth/register HTTP/1.1
content-type: application/json
Authorization: Bearer {{nonProdToken}}

{
    "username": "test123",
    "email": "user@strapi.io",
    "password": "xxxxxxxxxxxx"
}

### 1 of films
GET https://admin.poff.ee/films/3212 HTTP/1.1
content-type: application/json
Authorization: Bearer {{nonProdToken}}

### 1 of festival-editions
GET https://admin.poff.ee/festival-editions/66 HTTP/1.1
content-type: application/json
Authorization: Bearer {{nonProdToken}}

