### user profile endpoint
GET {{hunt_url}}/api/profile 
Authorization: Bearer {{nonProdToken}}

### all user-related data
GET {{hunt_url}}/api/me 
Authorization: Bearer {{nonProdToken}}

### Update user profile
put {{hunt_url}}/api/profile HTTP/1.1
Authorization: token {{nonProdToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="60x60bb.jpg"
Content-Type: image/jpg

< ./JonDoe.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstName"

Mihkel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastName"

Putrinš
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### forecast by city
GET https://api.openweathermap.org/data/2.5/forecast?q=TALLINN&appid=5927bae3714473ae1f6d7541cf67a948&units=metric

### weather by lat lon
GET https://api.openweathermap.org/data/2.5/weather?lat=59.437&lon=24.7535&appid=5927bae3714473ae1f6d7541cf67a948